### PR TITLE
Making color customization of different elements more accesible

### PR DESCRIPTION
**Pull request by PepeBigotes**
Makes so the user can easily edit the colors of elements like buttons, channels list, scrollbar, headers, ... 
Also facilitates colors assignation for said elements (so the user can assign one variable to different elements as he likes.
image

### CODE REVIEW

**Comment by PepeBigotes** [comment]
change the screenshot from the readme too btw

**Comment by CommandCrafterHD** [comment]
Since I just saw this, is this merge request still "valid" or active, since you mentioned it just being a fork in your readme?

**Comment by PepeBigotes** [comment]
> Since I just saw this, is this merge request still "valid" or active, since you mentioned it just being a fork in your readme?
I forgot this pull request is still active, i actually started developing this as a separated fork. But if you want i can try to make another, less conflictive pull request for this theme

**Comment by PepeBigotes** [comment]
Too much conflictive stuff, this is now a separated fork. Maybe there will be another pull request from me in the future.

**Pull request closed without merging**
